name: Node.js CI

on: 
  push:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: yarn
    - run: yarn test